// <auto-generated />
using System;
using DocumentManagerPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentManagerPersistence.Migrations
{
    [DbContext(typeof(DocumentContext))]
    [Migration("20260316120552_AddRules")]
    partial class AddRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DocumentManager.ContactDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RuleId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("DocumentManager.DocumentMetadataDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Checked")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Metadatas");
                });

            modelBuilder.Entity("DocumentManager.TagDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManualOnly")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DocumentManagerModel.DataMigrationDao", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("DataMigrations");
                });

            modelBuilder.Entity("DocumentManagerModel.DataMigrationErrorDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataMigrationDaoName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MigrationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataMigrationDaoName");

                    b.ToTable("DataMigrationErrors");
                });

            modelBuilder.Entity("DocumentManagerModel.Rule.RuleDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PredicateValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("DocumentMetadataDaoTagDao", b =>
                {
                    b.Property<Guid>("MetadatasId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("MetadatasId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("DocumentMetadataDaoTagDao");
                });

            modelBuilder.Entity("DocumentManager.ContactDao", b =>
                {
                    b.HasOne("DocumentManagerModel.Rule.RuleDao", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("DocumentManager.DocumentMetadataDao", b =>
                {
                    b.HasOne("DocumentManager.ContactDao", "Contact")
                        .WithMany("Metadatas")
                        .HasForeignKey("ContactId");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("DocumentManager.TagDao", b =>
                {
                    b.HasOne("DocumentManagerModel.Rule.RuleDao", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("DocumentManagerModel.DataMigrationErrorDao", b =>
                {
                    b.HasOne("DocumentManagerModel.DataMigrationDao", null)
                        .WithMany("Errors")
                        .HasForeignKey("DataMigrationDaoName");
                });

            modelBuilder.Entity("DocumentManagerModel.Rule.RuleDao", b =>
                {
                    b.HasOne("DocumentManagerModel.Rule.RuleDao", "Parent")
                        .WithMany("Operands")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DocumentMetadataDaoTagDao", b =>
                {
                    b.HasOne("DocumentManager.DocumentMetadataDao", null)
                        .WithMany()
                        .HasForeignKey("MetadatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManager.TagDao", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocumentManager.ContactDao", b =>
                {
                    b.Navigation("Metadatas");
                });

            modelBuilder.Entity("DocumentManagerModel.DataMigrationDao", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("DocumentManagerModel.Rule.RuleDao", b =>
                {
                    b.Navigation("Operands");
                });
#pragma warning restore 612, 618
        }
    }
}
