// <auto-generated />
using System;
using Messaging;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Messaging.Migrations
{
    [DbContext(typeof(MessagingContext))]
    [Migration("20260317155410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Messaging.MessageDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Messaging.MessageDao", b =>
                {
                    b.OwnsMany("Messaging.MessageSegment", "Segments", b1 =>
                        {
                            b1.Property<Guid>("MessageDaoId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.Property<string>("Url")
                                .IsRequired();

                            b1.HasKey("MessageDaoId", "__synthesizedOrdinal");

                            b1.ToTable("Messages");

                            b1
                                .ToJson("Segments")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("MessageDaoId");
                        });

                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
