import { Component, effect, inject, Input, OnInit } from '@angular/core';
import { MessageService } from '../message.service';

// =============================================================================
// NOTE: This Angular-based implementation is currently NOT in use.
// The plain JavaScript Web Component (messaging-toast.js) is used instead.
// Do not edit this file expecting changes to appear in the application.
// See messaging/messaging-toast.js for the active implementation.
// =============================================================================

@Component({
  selector: 'app-message-toast',
  imports: [],
  templateUrl: './message-toast.component.html',
  styleUrl: './message-toast.component.scss',
})
export class MessageToastComponent implements OnInit {
  @Input() apiBaseUrl = '';
  messageService = inject(MessageService);
  constructor() {
    effect(() => {
      const messages = this.messageService.messages();
      messages
        .filter((m) => m.severity === 'info')
        .forEach((m) => setTimeout(() => this.messageService.dismiss(m.id), 4000));
    });
  }

  ngOnInit(): void {
    this.messageService.initialize(this.apiBaseUrl);
  }
}
